services:
  ros-humble-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros-humble-vnc
    # Humble image needs this to launch correctly
    security_opt:
      - seccomp=unconfined
    shm_size: "1g"          # helps RViz/Gazebo stability
    network_mode: "host"
    volumes:
      - ros-volume:/home/ubuntu/ros_ws
    stdin_open: true
    tty: true
    platform: "linux/amd64"

volumes:
  ros-volume:
    external: true
